Rm2021/mobile/atchyuth/re tasks
mupputur/Mobile pull request #8
Opened 2021-02-28 09:21 UTC by Atchyutkumar-cmd

2021-03-01 14:38 UTC, mupputur requested changes

2021-03-01 14:38 UTC, mupputur commented on Atchyuth/adb_install.py
> +res=run_adb(cmd)
As discussed the test code should be deleted or commented or separated when we are implmneting a modules.
For example
if __name__ == "__main__":
   cmd='adb install C:\Andriod\platform-tools\cal.apk'
   cmd='adb install C:\Andriod\platform-tools\python_sample_mobile_app.apk'
   res=run_adb(cmd)
   res=run_adb(cmd)
   print(res)
   print(res)

2021-03-01 14:38 UTC, mupputur commented on Atchyuth/adb_install.py
> +def run_adb(cmd_list):
function names shoud be meaningful

In this case you can use install_app()

2021-03-01 14:38 UTC, mupputur commented on Atchyuth/adb_install.py
> +    res=None
As function is meant for installation , you can hardcode the command inside
def install_app(apk_path):
    res=None
    cmd = "adb install " + apk_path

2021-03-01 14:38 UTC, mupputur commented on Atchyuth/adb_install.py
> +cmd='adb install C:\Andriod\platform-tools\cal.apk'
Why you are installing same app twice ?

2021-03-01 14:38 UTC, mupputur commented on Atchyuth/adb_install.py
> +    except Exception as e:
Wrong exception handling

2021-03-01 14:38 UTC, mupputur commented on Atchyuth/adb_install.py
> +        res = subprocess.check_output(cmd)
This code can cause multiple exception. Please handle the excpected exceptions explicitly.

2021-03-02 14:02 UTC, Atchyutkumar-cmd commented on Atchyuth/adb_install.py
> +res=run_adb(cmd)
code is  modified as per suggestion

2021-03-02 14:03 UTC, Atchyutkumar-cmd commented on Atchyuth/adb_install.py
> +    res=None
modified the code

2021-03-02 14:05 UTC, Atchyutkumar-cmd commented on Atchyuth/adb_install.py
> +        res = subprocess.check_output(cmd)
Handled the expected exceptions explicitly in the code

2021-03-02 14:05 UTC, Atchyutkumar-cmd commented on Atchyuth/adb_install.py
> +    except Exception as e:
Modified the code

2021-03-02 14:16 UTC, mupputur commented on Atchyuth/1_install_apk.py
> +        if apk==True:
if not apk_path.endswith(".apk"):
   raise Exception("The file format should ends with .apk")

2021-03-02 14:30 UTC, mupputur approved these changes
Approved

2021-03-02 14:30 UTC, mupputur commented on Atchyuth/2_t2_ex1_current_running_processes.py
> +    fobj.close()
Please remove this and create a separate PR

2021-03-04 14:25 UTC, merged